// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: rpc/imserver/protos/servicedefinition/productinfo.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdList []string `protobuf:"bytes,1,rep,name=idList,proto3" json:"idList,omitempty"`
}

func (x *ProductInfoRequest) Reset() {
	*x = ProductInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfoRequest) ProtoMessage() {}

func (x *ProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfoRequest.ProtoReflect.Descriptor instead.
func (*ProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInfoRequest) GetIdList() []string {
	if x != nil {
		return x.IdList
	}
	return nil
}

type VariationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` //if numeric value, then convert it to string
	Unit  string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`   //if no unit then set empty string ("")
}

func (x *VariationResponse) Reset() {
	*x = VariationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariationResponse) ProtoMessage() {}

func (x *VariationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariationResponse.ProtoReflect.Descriptor instead.
func (*VariationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescGZIP(), []int{1}
}

func (x *VariationResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VariationResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type ProductShortInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mrp                   float32              `protobuf:"fixed32,3,opt,name=mrp,proto3" json:"mrp,omitempty"`
	ImageURL              string               `protobuf:"bytes,4,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	CategoryIdList        []string             `protobuf:"bytes,5,rep,name=categoryIdList,proto3" json:"categoryIdList,omitempty"`
	ParentId              string               `protobuf:"bytes,6,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ChildrenIdList        []string             `protobuf:"bytes,7,rep,name=childrenIdList,proto3" json:"childrenIdList,omitempty"`
	VariationResponseList []*VariationResponse `protobuf:"bytes,8,rep,name=variationResponseList,proto3" json:"variationResponseList,omitempty"`
}

func (x *ProductShortInfoResponse) Reset() {
	*x = ProductShortInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductShortInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductShortInfoResponse) ProtoMessage() {}

func (x *ProductShortInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductShortInfoResponse.ProtoReflect.Descriptor instead.
func (*ProductShortInfoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescGZIP(), []int{2}
}

func (x *ProductShortInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductShortInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductShortInfoResponse) GetMrp() float32 {
	if x != nil {
		return x.Mrp
	}
	return 0
}

func (x *ProductShortInfoResponse) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *ProductShortInfoResponse) GetCategoryIdList() []string {
	if x != nil {
		return x.CategoryIdList
	}
	return nil
}

func (x *ProductShortInfoResponse) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ProductShortInfoResponse) GetChildrenIdList() []string {
	if x != nil {
		return x.ChildrenIdList
	}
	return nil
}

func (x *ProductShortInfoResponse) GetVariationResponseList() []*VariationResponse {
	if x != nil {
		return x.VariationResponseList
	}
	return nil
}

type ProductShortInfoResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductShortInfoResponseList []*ProductShortInfoResponse `protobuf:"bytes,1,rep,name=productShortInfoResponseList,proto3" json:"productShortInfoResponseList,omitempty"`
}

func (x *ProductShortInfoResponseList) Reset() {
	*x = ProductShortInfoResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductShortInfoResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductShortInfoResponseList) ProtoMessage() {}

func (x *ProductShortInfoResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductShortInfoResponseList.ProtoReflect.Descriptor instead.
func (*ProductShortInfoResponseList) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescGZIP(), []int{3}
}

func (x *ProductShortInfoResponseList) GetProductShortInfoResponseList() []*ProductShortInfoResponse {
	if x != nil {
		return x.ProductShortInfoResponseList
	}
	return nil
}

var File_rpc_imserver_protos_servicedefinition_productinfo_proto protoreflect.FileDescriptor

var file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDesc = []byte{
	0x0a, 0x37, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x12,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x11, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0xb4, 0x02, 0x0a, 0x18, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x72,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x72, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x5a, 0x0a, 0x15, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x15, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x8f, 0x01, 0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x6f, 0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x1c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x32, 0x8d, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescOnce sync.Once
	file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescData = file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDesc
)

func file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescGZIP() []byte {
	file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescOnce.Do(func() {
		file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescData)
	})
	return file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDescData
}

var file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_imserver_protos_servicedefinition_productinfo_proto_goTypes = []interface{}{
	(*ProductInfoRequest)(nil),           // 0: servicedefinition.ProductInfoRequest
	(*VariationResponse)(nil),            // 1: servicedefinition.VariationResponse
	(*ProductShortInfoResponse)(nil),     // 2: servicedefinition.ProductShortInfoResponse
	(*ProductShortInfoResponseList)(nil), // 3: servicedefinition.ProductShortInfoResponseList
}
var file_rpc_imserver_protos_servicedefinition_productinfo_proto_depIdxs = []int32{
	1, // 0: servicedefinition.ProductShortInfoResponse.variationResponseList:type_name -> servicedefinition.VariationResponse
	2, // 1: servicedefinition.ProductShortInfoResponseList.productShortInfoResponseList:type_name -> servicedefinition.ProductShortInfoResponse
	0, // 2: servicedefinition.ProductInfoService.GetProductShortInfoByIdList:input_type -> servicedefinition.ProductInfoRequest
	3, // 3: servicedefinition.ProductInfoService.GetProductShortInfoByIdList:output_type -> servicedefinition.ProductShortInfoResponseList
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_imserver_protos_servicedefinition_productinfo_proto_init() }
func file_rpc_imserver_protos_servicedefinition_productinfo_proto_init() {
	if File_rpc_imserver_protos_servicedefinition_productinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductShortInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductShortInfoResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_imserver_protos_servicedefinition_productinfo_proto_goTypes,
		DependencyIndexes: file_rpc_imserver_protos_servicedefinition_productinfo_proto_depIdxs,
		MessageInfos:      file_rpc_imserver_protos_servicedefinition_productinfo_proto_msgTypes,
	}.Build()
	File_rpc_imserver_protos_servicedefinition_productinfo_proto = out.File
	file_rpc_imserver_protos_servicedefinition_productinfo_proto_rawDesc = nil
	file_rpc_imserver_protos_servicedefinition_productinfo_proto_goTypes = nil
	file_rpc_imserver_protos_servicedefinition_productinfo_proto_depIdxs = nil
}
