// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: rpc/imserver/protos/servicedefinition/productContainer.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductContainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdList []uint64 `protobuf:"varint,1,rep,packed,name=idList,proto3" json:"idList,omitempty"`
}

func (x *ProductContainerRequest) Reset() {
	*x = ProductContainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductContainerRequest) ProtoMessage() {}

func (x *ProductContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductContainerRequest.ProtoReflect.Descriptor instead.
func (*ProductContainerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescGZIP(), []int{0}
}

func (x *ProductContainerRequest) GetIdList() []uint64 {
	if x != nil {
		return x.IdList
	}
	return nil
}

type ProductContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ImageURL      string   `protobuf:"bytes,3,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	ProductIdList []string `protobuf:"bytes,4,rep,name=ProductIdList,proto3" json:"ProductIdList,omitempty"`
	Enabled       bool     `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *ProductContainer) Reset() {
	*x = ProductContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductContainer) ProtoMessage() {}

func (x *ProductContainer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductContainer.ProtoReflect.Descriptor instead.
func (*ProductContainer) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescGZIP(), []int{1}
}

func (x *ProductContainer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductContainer) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductContainer) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *ProductContainer) GetProductIdList() []string {
	if x != nil {
		return x.ProductIdList
	}
	return nil
}

func (x *ProductContainer) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ProductContainerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductContainerList []*ProductContainer `protobuf:"bytes,1,rep,name=productContainerList,proto3" json:"productContainerList,omitempty"`
}

func (x *ProductContainerResponse) Reset() {
	*x = ProductContainerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductContainerResponse) ProtoMessage() {}

func (x *ProductContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductContainerResponse.ProtoReflect.Descriptor instead.
func (*ProductContainerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescGZIP(), []int{2}
}

func (x *ProductContainerResponse) GetProductContainerList() []*ProductContainer {
	if x != nil {
		return x.ProductContainerList
	}
	return nil
}

var File_rpc_imserver_protos_servicedefinition_productContainer_proto protoreflect.FileDescriptor

var file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x31, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x69, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x94, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x24, 0x0a, 0x0d, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x73, 0x0a, 0x18, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x14, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x32, 0x97, 0x01, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7c, 0x0a, 0x1f,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x69, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescOnce sync.Once
	file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescData = file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDesc
)

func file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescGZIP() []byte {
	file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescOnce.Do(func() {
		file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescData)
	})
	return file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDescData
}

var file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_imserver_protos_servicedefinition_productContainer_proto_goTypes = []interface{}{
	(*ProductContainerRequest)(nil),  // 0: servicedefinition.ProductContainerRequest
	(*ProductContainer)(nil),         // 1: servicedefinition.ProductContainer
	(*ProductContainerResponse)(nil), // 2: servicedefinition.ProductContainerResponse
}
var file_rpc_imserver_protos_servicedefinition_productContainer_proto_depIdxs = []int32{
	1, // 0: servicedefinition.ProductContainerResponse.productContainerList:type_name -> servicedefinition.ProductContainer
	0, // 1: servicedefinition.ProductContainerService.GetProductContainerListByIdList:input_type -> servicedefinition.ProductContainerRequest
	2, // 2: servicedefinition.ProductContainerService.GetProductContainerListByIdList:output_type -> servicedefinition.ProductContainerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_imserver_protos_servicedefinition_productContainer_proto_init() }
func file_rpc_imserver_protos_servicedefinition_productContainer_proto_init() {
	if File_rpc_imserver_protos_servicedefinition_productContainer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductContainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductContainerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_imserver_protos_servicedefinition_productContainer_proto_goTypes,
		DependencyIndexes: file_rpc_imserver_protos_servicedefinition_productContainer_proto_depIdxs,
		MessageInfos:      file_rpc_imserver_protos_servicedefinition_productContainer_proto_msgTypes,
	}.Build()
	File_rpc_imserver_protos_servicedefinition_productContainer_proto = out.File
	file_rpc_imserver_protos_servicedefinition_productContainer_proto_rawDesc = nil
	file_rpc_imserver_protos_servicedefinition_productContainer_proto_goTypes = nil
	file_rpc_imserver_protos_servicedefinition_productContainer_proto_depIdxs = nil
}
